[tool.flake8]
max-line-length = 110
max-complexity = 10
ignore = [
    'W503',
    'ANN002',
    'ANN003',
    # Missing type annotation for self,cls in method
    'ANN101',
    'ANN102',
    # Missing return type annotation for public function
    'ANN201',
    'ANN202',
    # Missing return type annotation for special method
    'ANN204',
    # Missing return type annotation for public function
    'ANN205',
]

per-file-ignores = [
    'netads/tests/base.py:T001,T201',
    'netads/tests/feedbacks.py:T201',
    'netads/tests/runner.py:T001,T201',
    'netads/tests/test_import.py:T001',
]

exclude = [
    '.git',
    '.venv',
    'venv/',
    '__pycache__,',
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
lines_between_types = 1
skip = [
    '.venv',
    'venv',
]

[tool.qgis-plugin-ci]
plugin_path = "netads"
github_organization_slug = "3liz"
project_slug = "qgis-netads-plugin"

[tool.pylint]
disable = [
    'C0114',
    'E0401',
    'E0611',
]
